const fs = require('fs');
let content = `\n`;
content += `    const clickTh = async (label) => {\n`;
content += `      const th = findByLabel(label);\n`;
content += `      if (!th) return null;\n`;
content += `      const btn = th.querySelector('button');\n`;
content += `      await act(async () => { btn.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true })); });\n`;
content += `      await flush();\n`;
content += `      await act(async () => { await flush(); });\n`;
content += `      return findByLabel(label);\n`;
content += `    };\n`;
content += `    let th = await clickTh('Nome');\n`;
content += `    let p = lastList()?.params;\n`;
content += `    check('1 clique em Nome → sort=nome dir=asc', !!p && p.get('sort') === 'nome' && p.get('dir') === 'asc');\n`;
content += `    check('indicador asc no cabecalho ativo', !!th && th.textContent.includes('arrow_upward'));\n`;
content += `    const asc = rowsNome();\n`;
content += `    const ascSorted = [...asc].sort((a, b) => a.localeCompare(b, 'pt-BR', { sensitivity: 'base' }));\n`;
content += `    check('linhas em ordem crescente', JSON.stringify(asc) === JSON.stringify(ascSorted));\n`;
content += `    th = await clickTh('Nome');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('2 clique em Nome → sort=nome dir=desc', !!p && p.get('sort') === 'nome' && p.get('dir') === 'desc');\n`;
content += `    check('indicador desc no cabecalho ativo', !!th && th.textContent.includes('arrow_downward'));\n`;
content += `    const desc = rowsNome();\n`;
content += `    check('linhas em ordem decrescente', JSON.stringify(desc) === JSON.stringify([...desc].sort((a, b) => b.localeCompare(a, 'pt-BR', { sensitivity: 'base' })));\n`;
content += `    await clickTh('Nome');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('3 clique → estado padrao (sem sort/dir)', !!p && !p.get('sort') && !p.get('dir'));\n`;
content += `    await clickTh('Setor');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('clique em Setor → sort=setor dir=asc', !!p && p.get('sort') === 'setor' && p.get('dir') === 'asc');\n`;
content += `    await clickTh('Cargo');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('clique em Cargo → sort=cargo', !!p && p.get('sort') === 'cargo');\n`;
content += `    await clickTh('Status');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('clique em Status → sort=ativo', !!p && p.get('sort') === 'ativo');\n`;
content += `    const search = container.querySelector('input[aria-label^="Buscar"]');\n`;
content += `    if (search) { setVal(search, 'ana'); await flush(); }\n`;
content += `    const setorSel = container.querySelector('select[aria-label="Filtrar por setor"]');\n`;
content += `    if (setorSel) {\n`;
content += `      setVal(setorSel, '2');\n`;
content += `      const form = container.querySelector('#func-filters');\n`;
content += `      await act(async () => { form.dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true })); });\n`;
content += `      await flush();\n`;
content += `      await act(async () => { await flush(); });\n`;
content += `    }\n`;
content += `    await clickTh('Nome');\n`;
content += `    p = lastList()?.params;\n`;
content += `    check('combinacao pesquisa + filtro setor + sort nome', !!p && p.get('search') === 'ana' && p.get('setor_id') === '2' && p.get('sort') === 'nome');\n`;
content += `    const btnLimpar = [...container.querySelectorAll('#func-filters button')].find((b) => b.textContent.trim() === 'Limpar');\n`;
content += `    if (btnLimpar) {\n`;
content += `      await act(async () => { btnLimpar.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true })); });\n`;
content += `      await flush();\n`;
content += `      await act(async () => { await flush(); });\n`;
content += `    }\n`;
content += `    check('estado inicial sem ordenacao ativa', !findByLabel('Nome')?.textContent.includes('arrow_upward'));\n`;
content += `  } finally {\n`;
content += `    globalThis.fetch = realFetch;\n`;
content += `  }\n`;
content += `}\n`;
fs.appendFileSync('.smoke/funcionarios.mjs', content, 'utf8');
console.log('Parte 4 OK');
