const fs = require('fs');
let content = `\n`;
content += `  const calls = [];\n`;
content += `  const realFetch = globalThis.fetch;\n`;
content += `  globalThis.fetch = async (url) => {\n`;
content += `    const u = new URL(String(url), 'http://localhost');\n`;
content += `    const endpoint = u.searchParams.get('endpoint');\n`;
content += `    const action = u.searchParams.get('action');\n`;
content += `    calls.push({ endpoint, action, params: u.searchParams });\n`;
content += `    let data = null;\n`;
content += `    if (endpoint === 'funcionarios' && action === 'listar') data = applyList(u.searchParams);\n`;
content += `    else if (endpoint === 'setores' && action === 'listar') data = { items: [{ id: 1, nome: 'TI', ativo: 1 }, { id: 2, nome: 'DOCA', ativo: 1 }], total: 2, page: 1, limit: 200, total_pages: 1 };\n`;
content += `    else data = { items: [], total: 0, page: 1, limit: 20, total_pages: 0 };\n`;
content += `    return { ok: true, status: 200, json: async () => ({ success: true, data }) };\n`;
content += `  };\n`;
content += `  try {\n`;
content += `    const thLabel = (th, label) => th.textContent.replace(/\s*swap_vert\s*/g, '').replace(/\s*arrow_upward\s*/g, '').replace(/\s*arrow_downward\s*/g, '').trim() === label;\n`;
content += `    const findByLabel = (label) => [...container.querySelectorAll('th')].find((th) => thLabel(th, label));\n`;
content += `    const rowsNome = () => [...container.querySelectorAll('.func-name')].map((el) => el.textContent.replace(/\s*\u2014\s*$/, '').trim());\n`;
content += `    const lastList = () => (calls.length ? calls[calls.length - 1] : null);\n`;
content += `    const flush = () => new Promise((r) => setTimeout(r, 5));\n\n`;
content += `    window.location.hash = '#/funcionarios';\n`;
content += `    await act(async () => { await flush(); });\n`;
content += `    await flush();\n\n`;
content += `    const esperados = ['Nome', 'Cargo', 'Setor', 'RG', 'E-mail', 'Status', 'Acoes'];\n`;
content += `    const faltando = esperados.filter((l) => !findByLabel(l));\n`;
content += `    check('cabeçalhos renderizados', faltando.length === 0 ? 'cabeçalhos encontrados' : 'faltando: ' + faltando.join(', '));\n`;
content += `    const nomeTh = findByLabel('Nome');\n`;
content += `    check('coluna Nome usa componente ordenavel', !!nomeTh && !!nomeTh.querySelector('.th-sort'));\n`;
fs.appendFileSync('.smoke/funcionarios.mjs', content, 'utf8');
console.log('Parte 3 OK');
