const fs = require('fs');
let content = ``;
content += `  const SORTABLE = { nome: 'nome', cargo: 'cargo', setor: 'setor_nome', rg: 'rg', email: 'email', ativo: 'ativo' };\n\n`;
content += `  function applyList(p) {\n`;
content += `    const limit = Math.min(200, Math.max(1, Number(p.get('limit') || 20)));\n`;
content += `    const page = Math.max(1, Number(p.get('page') || 1));\n`;
content += `    let rows = DB.slice();\n`;
content += `    const search = (p.get('search') || '').trim().toLowerCase();\n`;
content += `    if (search) rows = rows.filter((r) => [r.nome, r.cargo, r.setor_nome].some((v) => String(v || '').toLowerCase().includes(search)));\n`;
content += `    if (p.get('setor_id')) rows = rows.filter((r) => String(r.setor_id || '') === p.get('setor_id'));\n`;
content += `    if (p.get('ativo') !== null && p.get('ativo') !== undefined && p.get('ativo') !== '') rows = rows.filter((r) => String(r.ativo) === p.get('ativo'));\n`;
content += `    const sort = p.get('sort');\n`;
content += `    const dir = (p.get('dir') || 'asc').toLowerCase() === 'desc' ? -1 : 1;\n`;
content += `    if (sort && SORTABLE[sort]) {\n`;
content += `      const key = SORTABLE[sort];\n`;
content += `      rows.sort((a, b) => {\n`;
content += `        const av = a[key]; const bv = b[key];\n`;
content += `        const an = av === null || av === undefined || av === '';\n`;
content += `        const bn = bv === null || bv === undefined || bv === '';\n`;
content += `        if (an && bn) return b.id - a.id;\n`;
content += `        if (an) return -1;\n`;
content += `        if (bn) return 1;\n`;
content += `        const cmp = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv), 'pt-BR', { sensitivity: 'base', numeric: true });\n`;
content += `        return cmp !== 0 ? cmp * dir : b.id - a.id;\n`;
content += `      });\n`;
content += `    } else { rows.sort((a, b) => b.id - a.id); }\n`;
content += `    const total = rows.length;\n`;
content += `    const items = rows.slice((page - 1) * limit, (page - 1) * limit + limit);\n`;
content += `    return { items, total, page, limit, total_pages: Math.max(1, Math.ceil(total / limit)) };\n`;
content += `  }\n`;
fs.appendFileSync('.smoke/funcionarios.mjs', content, 'utf8');
console.log('Parte 2 OK');
